src/Entity/Address.php
<?php

namespace App\Entity;

use ApiPlatform\Doctrine\Orm\Filter\OrderFilter;
use ApiPlatform\Doctrine\Orm\Filter\SearchFilter;
use ApiPlatform\Metadata\ApiFilter;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use App\Filter as CustomFilter;
use App\Repository\AddressRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Intl\Countries;
use \RuntimeException;

#[ORM\Entity(repositoryClass: AddressRepository::class)]
#[ApiResource(
    operations: [
        new Get(
            uriTemplate: '/address/{id}',
            requirements: ['id' => '\d+'],
            security: "is_granted('".Role::ROLE_ADMIN."') or (is_granted('".Role::ROLE_USER."') and object.getAddressUser() == user)",
            normalizationContext: ['groups' => ['address-details']]
        ),
        new GetCollection(
            uriTemplate: '/address',
            normalizationContext: ['groups' => ['address-list']]
        )
    ],
    normalizationContext: ['groups' => ['address-list','address-details']],
    denormalizationContext: ['groups' => ['address-write']],
)]
#[ApiFilter(
    SearchFilter::class, properties: [
        'addressCompany.id' => 'exact', 'countryCode' => 'exact',
        'addressUser.id' => 'exact'
    ]
)]
#[ApiFilter(CustomFilter\AddressKeywordSearchFilter::class, properties: [Address::ADDRESS_KEYWORD_SEARCH])]
#[ApiFilter(OrderFilter::class, properties: ['id' => 'ASC', 'name' => 'DESC'])]
class Address
{
    public const ADDRESS_KEYWORD_SEARCH = 'address_keyword_search';

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['address-list','address-details','company-details','user-list','user-details','company-representation-list','company-representation-details'])]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Groups(['address-list','address-details','company-details','user-details'])]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    #[Groups(['address-list','address-details','company-list','company-details','user-details','company-representation-details'])]
    private ?string $address = null;

    #[ORM\Column(length: 10, nullable: true)]
    #[Groups(['address-list','address-details','company-list','company-details','user-details','company-representation-details'])]
    private ?string $postCode = null;

    #[ORM\Column(length: 50)]
    #[Groups(['address-list','address-details','company-list','company-details','user-list','user-details','company-representation-list','company-representation-details'])]
    private ?string $city = null;

    #[ORM\Column(length: 2)]
    #[Groups(['address-list','address-details','company-list','company-details','user-list','user-details','company-representation-list','company-representation-details'])]
    private ?string $countryCode = null;

    #[ORM\Column(length: 50, nullable: true)]
    #[Groups(['address-list','address-details','company-list','company-details','user-list','user-details','company-representation-details'])]
    private ?string $phoneNumber = null;

    #[ORM\OneToOne(mappedBy: 'address', cascade: ['persist', 'remove'])]
    #[Groups(['address-list','address-details'])]
    private ?Company $addressCompany = null;

    #[ORM\OneToOne(mappedBy: 'address', cascade: ['persist', 'remove'])]
    #[Groups(['address-list','address-details'])]
    private ?User $addressUser = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): static
    {
        $this->address = $address;

        return $this;
    }

    public function getPostCode(): ?string
    {
        return $this->postCode;
    }

    public function setPostCode(?string $postCode): static
    {
        $this->postCode = $postCode;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): static
    {
        $this->city = $city;

        return $this;
    }

    public function getCountryCode(): ?string
    {
        return $this->countryCode;
    }

    public function setCountryCode(string $countryCode): static
    {
        $this->countryCode = $countryCode;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phoneNumber;
    }

    public function setPhoneNumber(?string $phoneNumber): static
    {
        $this->phoneNumber = $phoneNumber;

        return $this;
    }

    public function getAddressCompany(): ?Company
    {
        return $this->addressCompany;
    }

    public function setAddressCompany(Company $company): static
    {
        // set the owning side of the relation if necessary
        if ($company->getAddress() !== $this) {
            $company->setAddress($this);
        }

        $this->addressCompany = $company;

        return $this;
    }

    public function getAddressUser(): ?User
    {
        return $this->addressUser;
    }

    public function setAddressUser(User $addressUser): static
    {
        // set the owning side of the relation if necessary
        if ($addressUser->getAddress() !== $this) {
            $addressUser->setAddress($this);
        }

        $this->addressUser = $addressUser;

        return $this;
    }

    #[Groups(['address-list','address-details','company-list','user-list','user-details','company-representation-list','company-representation-details'])]
    public function getCountry(): ?string
    {
        try {
            return Countries::getName($this->countryCode);
        } catch(RuntimeException $e) {
            return null;
        }
    }

    #[Groups(['address-list','address-details','company-list','user-list','user-details','company-representation-list','company-representation-details'])]
    public function getAlpha3(): ?string
    {
        try {
            return Countries::getAlpha3Code($this->countryCode);
        } catch(RuntimeException $e) {
            return null;
        }
    }
}

src/Entity/ContractTemplate.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use App\Controller\ContractTemplate\ViewContractTemplateAction;
use App\Controller\ContractTemplate\ViewBillTemplateAction;
use App\Repository\ContractTemplateRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Intl\Languages;
use \RuntimeException;

#[ORM\Entity(repositoryClass: ContractTemplateRepository::class)]
#[ApiResource(
    operations: [
        new Get(
            uriTemplate: '/contract/template/{id}',
            name: 'contract-template-view',
            requirements: ['id' => '\d+'],
            security: "is_granted('".Role::ROLE_ADMIN."')",
            normalizationContext: ['groups' => ['contract-template-details']]
        ),
        new Get(
            uriTemplate: '/contract/template/{id}/contract',
            name: 'contract-template-contract',
            requirements: ['id' => '\d+'],
            security: "is_granted('".Role::ROLE_ADMIN."')",
            controller: ViewContractTemplateAction::class,
        ),
        new Get(
            uriTemplate: '/contract/template/{id}/bill',
            name: 'contract-template-bill',
            requirements: ['id' => '\d+'],
            security: "is_granted('".Role::ROLE_ADMIN."')",
            controller: ViewBillTemplateAction::class,
        ),
        new GetCollection(
            uriTemplate: '/contract/template',
            security: "is_granted('".Role::ROLE_ADMIN."')",
            normalizationContext: ['groups' => ['contract-template-list']]
        )
    ],
    normalizationContext: ['groups' => ['contract-template-list','contract-template-list-details']],
    denormalizationContext: ['groups' => ['contract-template-write']],
)]
class ContractTemplate
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['contract-template-list','contract-template-details'])]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Groups(['contract-template-list','contract-template-details'])]
    private ?string $name = null;

    #[ORM\Column(length: 5)]
    #[Groups(['contract-template-list','contract-template-details'])]
    private ?string $languageCode = null;

    #[ORM\Column(length: 255)]
    #[Groups(['contract-template-details'])]
    private ?string $contractTemplatePath = null;

    #[ORM\Column(length: 255)]
    #[Groups(['contract-template-details'])]
    private ?string $billTemplatePath = null;

    #[ORM\OneToMany(mappedBy: 'contractTemplate', targetEntity: Contract::class)]
    private Collection $contracts;

    public function __construct()
    {
        $this->contracts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getLanguageCode(): ?string
    {
        return $this->languageCode;
    }

    public function setLanguageCode(string $languageCode): static
    {
        $this->languageCode = $languageCode;

        return $this;
    }

    public function getContractTemplatePath(): ?string
    {
        return $this->contractTemplatePath;
    }

    public function setContractTemplatePath(string $contractTemplatePath): static
    {
        $this->contractTemplatePath = $contractTemplatePath;

        return $this;
    }

    public function getBillTemplatePath(): ?string
    {
        return $this->billTemplatePath;
    }

    public function setBillTemplatePath(string $billTemplatePath): static
    {
        $this->billTemplatePath = $billTemplatePath;

        return $this;
    }

    /**
     * @return Collection<int, Contract>
     */
    public function getContracts(): Collection
    {
        return $this->contracts;
    }

    public function addContract(Contract $contract): static
    {
        if (!$this->contracts->contains($contract)) {
            $this->contracts->add($contract);
            $contract->setContractTemplate($this);
        }

        return $this;
    }

    public function removeContract(Contract $contract): static
    {
        if ($this->contracts->removeElement($contract)) {
            // set the owning side to null (unless already changed)
            if ($contract->getContractTemplate() === $this) {
                $contract->setContractTemplate(null);
            }
        }

        return $this;
    }

    #[Groups(['contract-template-list','contract-template-details'])]
    public function getLanguage(): ?string
    {
        try {
            return Languages::getName($this->languageCode);
        } catch(RuntimeException $e) {
            return null;
        }
    }
}

src/Controller/ContractTemplate/BaseViewAction.php
<?php

declare(strict_types=1);

namespace App\Controller\ContractTemplate;

use App\Core\ContractTemplate\Model\ContractTemplate;
use Knp\Snappy\Pdf;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Attribute\AsController;

#[AsController]
class BaseViewAction extends AbstractController
{

    protected string $_filePath = '';

    protected string $_fileNamePattern = '';

    public function __construct(
        private readonly Pdf $pdf,
    )
    {
    }

    public function renderTemplate(Request $request, ContractTemplate $data) : Response
    {
        $content = $this->renderView($this->_filePath, []);

        $pdfContent = $this->pdf->getOutputFromHtml($content, []);

        $fileName = sprintf($this->_fileNamePattern, $data->getId(), $data->getLanguageCode());

        $response = new Response($pdfContent);
        $response->headers->set('Content-type', 'application/octet-stream');
        $response->headers->set('Content-Disposition', sprintf('attachment; filename="%s"', $fileName));
        $response->headers->set('Content-Transfer-Encoding', 'binary');
        return $response;
    }
}

src/Controller/ContractTemplate/ViewBillTemplateAction.php
<?php

declare(strict_types=1);

namespace App\Controller\ContractTemplate;

use App\Core\ContractTemplate\Model\ContractTemplate;
use Knp\Snappy\Pdf;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Attribute\AsController;

#[AsController]
final class ViewBillTemplateAction extends BaseViewAction
{

    private const TEMPLATE_FILE_NAME = 'bill-template-%s-%s.pdf';

    public function __invoke(Request $request, ContractTemplate $data) : Response
    {
        $this->_filePath = 'contract-template/'.$data->getBillTemplatePath();
        $this->_fileNamePattern = self::TEMPLATE_FILE_NAME;

        return $this->renderTemplate($request, $data);
    }
}

src/Controller/ContractTemplate/ViewContractTemplateAction.php
<?php

declare(strict_types=1);

namespace App\Controller\ContractTemplate;

use App\Core\ContractTemplate\Model\ContractTemplate;
use Knp\Snappy\Pdf;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Attribute\AsController;

#[AsController]
final class ViewContractTemplateAction extends BaseViewAction
{

    private const TEMPLATE_FILE_NAME = 'contract-template-%s-%s.pdf';

    private const TEMPLATE_DIR = 'contract-template/';


    public function generateBillTemplate(ContractTemplate $data): void
    {
        $this->_filePath = self::TEMPLATE_DIR.$data->getBillTemplatePath();
        $this->_fileNamePattern = self::TEMPLATE_FILE_NAME;
    }

    public function generateContractTemplate(ContractTemplate $data): void
    {
        $this->_filePath = self::TEMPLATE_DIR.$data->getContractTemplatePath();
        $this->_fileNamePattern = self::TEMPLATE_FILE_NAME;
    }

    public function __invoke(Request $request, ContractTemplate $data) : Response
    {
        $this->_fileNamePattern = self::TEMPLATE_FILE_NAME;
        $this->_filePath = self::TEMPLATE_DIR.$data->getContractTemplatePath();

        return $this->renderTemplate($request, $data);
    }
}

templates/contract-template/base.html.twig
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Contract template</title>
    <link href="https://fonts.googleapis.com/css2?family=Kumbh+Sans:wght@400;700&display=swap" rel="stylesheet">
</head>
{% block stylesheets %}
{% include 'components/pdf-styles.html.twig' %}
{% endblock %}
<body>
{% block contract %}
{% endblock %}
</body>
</html>

templates/contract-template/bill_en.html.twig
{% extends 'contract-template/base.html.twig' %}
{% block stylesheets %}
{% include 'components/pdf-styles.html.twig' %}
{% include 'components/pdf-bill-styles.html.twig' %}
{% endblock %}
{% block contract %}
<table cellspacing="0" border="0" width="100%">
    <colgroup span="3" width="67"></colgroup>
    <colgroup width="24"></colgroup>
    <colgroup span="2" width="132"></colgroup>
    <tr>
        <td height="13" align="left" colspan="3"><strong>Issuer</strong></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
    </tr>
    <tr>
        <td height="19" align="left" colspan="3"><strong>{{ contract.contractor.firstname|default("Firstname") }} {{ contract.contractor.lastname|default("Lastname") }}</strong></td>
        <td align="right" colspan="3"><strong><font size=4>Invoice for a work contract</font></strong></td>
    </tr>
    <tr>
        <td height="13" align="left" colspan="3">
            {{ contract.contractor.address.address|default("Address") }}, {{ contract.contractor.address.postCode|default("post code") }} {{ contract.contractor.address.city|default("city") }},
            {{ contract.contractor.address.country|default("country") }}
        </td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
    </tr>
    <tr>
        <td height="13" align="left" colspan="3">PESEL: {{ contract.contractor.pesel|default("PESEL") }}</td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
    </tr>
    <tr>
        <td height="13" align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
    </tr>
    <tr>
        <td height="13" align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
    </tr>
    <tr>
        <td height="13" align="left" colspan="3"><strong>Recipient</strong></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
    </tr>
    <tr>
        <td height="13" align="left" colspan="3">
            <strong>{{ contract.company.name|default("Company name") }}</strong>
        </td>
        <td align="left"><br></td>
        <td class="borderded-cell gray-bg" align="center">
            <strong>Invoice number</strong>
        </td>
        <td class="borderded-cell gray-bg" align="center">
            <strong>Date</strong>
        </td>
    </tr>
    <tr>
        <td height="13" align="left" colspan="3">
             {{ contract.company.address.address|default("Adres") }}, {{ contract.company.address.postCode|default("kod pocztowy") }} {{ contract.company.address.city|default("miasto") }},
            {{ contract.company.address.country|default("państwo") }}
        </td>
        <td align="left"><br></td>
        <td class="borderded-cell" align="center">
            {{ contract.contractNumber|default("Invoice number") }}
        </td>
        <td class="borderded-cell" align="center" sdval="43924" sdnum="1033;0;D/MM/YYYY">
            <strong>
            {% if contract.paidAt is defined %}
            {{ contract.paidAt|date('d.m.Y') }}
            {% else %}
            Issuance date
            {% endif %}
            </strong>
        </td>
    </tr>
    <tr>
        <td height="13" align="left" colspan="3">NIP: {{ contract.company.vatin|default("NIP") }}</td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
    </tr>
    <tr>
        <td height="13" align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
    </tr>
    <tr>
        <td class="borderded-cell gray-bg vertical-align-middle" colspan=5 height="15" align="center">
            <strong>Description</strong>
        </td>
        <td class="borderded-cell gray-bg" align="center">
            <strong>Gross amount</strong>
        </td>
    </tr>
    <tr>
        <td class="borderded-cell vertical-align-middle" colspan=5 height="48" align="left">
            {{ contract.subject|default("Subject of the contract") }}
        </td>
        <td class="borderded-cell" align="right">
            {% if contract.valueGross is defined %}
            {{ (contract.valueGross / 100)|number_format(2,',',' ') }}
            {% else %}
            Gross amount
            {% endif %}
            zł
        </td>
    </tr>
    <tr>
        <td class="borderded-cell vertical-align-middle" colspan=5 height="15" align="right">
            <strong>TOTAL:</strong>
        </td>
        <td class="borderded-cell" align="right">
            {% if contract.valueGross is defined %}
            {{ (contract.valueGross / 100)|number_format(2,',',' ') }}
            {% else %}
            Total gross
            {% endif %}
            zł
        </td>
    </tr>
    <tr>
        <td height="13" align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
    </tr>
    <tr>
        <td height="13" align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
    </tr>
    <tr>
        <td class="borderded-cell gray-bg vertical-align-middle" colspan=5 height="15" align="center">
            <strong>Settlement</strong>
        </td>
        <td class="borderded-cell gray-bg" align="center">
            <strong>Amount</strong>
        </td>
    </tr>
    <tr>
        <td class="borderded-cell vertical-align-middle" colspan=5 height="13" align="right">
            Gross value:
        </td>
        <td class="borderded-cell" align="right">
            {% if contract.valueGross is defined %}
            {{ (contract.valueGross / 100)|number_format(2,',',' ') }}
            {% else %}
            Total gross
            {% endif %}
            zł
        </td>
    </tr>
    <tr>
        <td class="borderded-cell vertical-align-middle" colspan=5 height="13" align="right">
            Income acquisition costs (50%)
        </td>
        <td class="borderded-cell" align="right">
            {% if contract.valueGross is defined %}
            {{ (contract.valueGross / 200)|number_format(2,',',' ') }}
            {% else %}
            Income acquisition costs
            {% endif %}
        </td>
    </tr>
    <tr>
        <td class="borderded-cell vertical-align-middle" colspan=5 height="13" align="right">
            Tax advance:
        </td>
        <td class="borderded-cell" align="right">
            {% if contract.valueTax is defined %}
            {{ (contract.valueTax / 100)|number_format(2,',',' ') }}
            {% else %}
            Tax amount
            {% endif %}
            zł
        </td>
    </tr>
    <tr>
        <td class="borderded-cell vertical-align-middle" colspan=5 height="13" align="right">
            Do wypłaty:
        </td>
        <td class="borderded-cell" align="right">
            {% if contract.valueNet is defined %}
            {{ (contract.valueNet / 100)|number_format(2,',',' ') }}
            {% else %}
            To be paid out
            {% endif %}
            zł
        </td>
    </tr>
    <tr>
        <td height="15" align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
    </tr>
    <tr>
        <td height="13" align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
    </tr>
    <tr>
        <td height="13" align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
    </tr>
    <tr>
        <td height="13" align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
    </tr>
    <tr>
        <td height="13" align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
    </tr>
    <tr>
        <td height="13" align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
    </tr>
    <tr>
        <td height="13" align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="left">…………………………………</td>
    </tr>
    <tr>
        <td height="13" align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="center">Issuer's signature</td>
    </tr>
    <tr>
        <td height="13" align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
    </tr>
    <tr>
        <td height="13" align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
    </tr>
    <tr>
        <td height="13" align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
    </tr>
    <tr>
        <td height="13" align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
        <td align="left"><br></td>
    </tr>
    <tr>
        <td height="15" align="left" colspan="6">
            Bank account: {{ contract.contractrorBankAccout.bankName|default("Bank") }} {{ contract.contractrorBankAccout.accountNumber|default("Numer rachunku") }}
        </td>
    </tr>
</table>
{% endblock %}